### ISSUE TITLE
500 Endpoint terminated error

### ISSUE THREAD

**Issue by yalegria** [mozilla/reticulum#173]
While installing and executing $DB_HOST docker_compose up I am getting the following output on the terminal:

ret_1  | [info] GET /                                                                                                                                                                                          
ret_1  | [info] Sent 500 in 24ms
ret_1  | [error] #PID<0.2351.0> running RetWeb.Endpoint (cowboy_protocol) terminated
ret_1  | Server: 172.16.180.147:4000 (https)
ret_1  | Request: GET /
ret_1  | ** (exit) an exception was raised:
ret_1  |     ** (ArgumentError) response body cannot be set to nil
ret_1  |         (plug) lib/plug/conn.ex:583: Plug.Conn.resp/3
ret_1  |         (plug) lib/plug/conn.ex:555: Plug.Conn.send_resp/3
ret_1  |         (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
ret_1  |         (ret) lib/plug/error_handler.ex:64: RetWeb.Router.call/2
ret_1  |         (ret) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint.plug_builder_call/2
ret_1  |         (ret) lib/plug/debugger.ex:122: RetWeb.Endpoint."call (overridable 3)"/2
ret_1  |         (ret) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint."call (overridable 4)"/2
ret_1  |         (ret) lib/ret_web/endpoint.ex:1: RetWeb.Endpoint.call/2
ret_1  |         (plug_cowboy) lib/plug/cowboy/handler.ex:18: Plug.Adapters.Cowboy.Handler.upgrade/4
ret_1  |         (cowboy) /ret/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

Same output is displayed on the browser: http://localhost:4000

Any thoughts?

**Comment by brianpeiris** [comment]
We ended up discussing this directly in Discord. This error occurs because reticulum expects there to be a local instance of the [Hubs client](https://github.com/mozilla/hubs) running at `hubs.local:8080`, from which it retrieves HTML pages.

I'll close this for now. Feel free to open another issue if you run into other problems.
