### ISSUE TITLE
Migrations can fail to run when server under load

### ISSUE THREAD

**Issue by gfodor** [mozilla/reticulum#346]
Migrations will fail if the server is getting hit when starting up and errors are flying out because database is out of date.

probably boils down to integrating something like https://github.com/mspanc/ecto_boot_migration

**Comment by blairmacintyre** [comment]
It would be REALLY good if there was a way in the admin panel to "close" the site temporarily, esp for hubs-cloud.  Something like shutdown on unix:  enter a reasons (WHATEVER REASON) and time (default 60, could be 0, seconds), and everyone starts getting "system shutting down (WHATEVER REASON) in 60, 59, ...) then everyone is kicked.

Landing page should change immediately to a message, and all new entry prohibited.

**Comment by gfodor** [comment]
You can do this - in the stack, flip the site to offline mode. It can
redirect to a url.
