### ISSUE TITLE
serve responses with 404 (instead of 500) error code for invalid URL routes

### ISSUE THREAD

**Issue by cvan** [mozilla/reticulum#35]
1. load an invalid route, such as https://hubs.mozilla.com/404 or https://hubs.mozilla.com/google4afac22ec4cd831b.html (from [Google's `robots.txt` tester](https://support.google.com/webmasters/answer/6062598?hl=en&ref_topic=6061961))
2. notice a 500 Internal Server Error response is seen (not a 404 Not Found)

![Screenshot of 500 curl call in the terminal](https://user-images.githubusercontent.com/203725/40145339-053dc704-5927-11e8-9deb-e0b380f2fdb3.png)
![Screenshot of 500 page in Firefox](https://user-images.githubusercontent.com/203725/40145342-0805e8ea-5927-11e8-8f26-abd0ed0178c5.png)

**Comment by brianpeiris** [comment]
This must have been fixed at some point. We return 404s as expected now.
