### ISSUE TITLE
(ArgumentError) argument error:

### ISSUE THREAD

**Issue by zhang-wenhua** [mozilla/reticulum#369]
[error] GenServer #PID<0.3890.0> terminating
** (ArgumentError) argument error: [[], {:jose_jws, {:jose_jws_alg_rsa_pkcs1_v1_5, :RS512}, :undefined, %{"typ" => "JWT"}}, %{"aud" => :ret_perms, "create_hub" => true, "exp" => 1587718257, "iat" => 1587717957, "iss" => "", "jti" => "60fd98da-244a-4f08-a6ca-cc2600d1320e", "nbf" => 1587717956, "sub" => "anon", "tweet" => false, "typ" => "access"}]
    (jose 1.10.1) src/jwt/jose_jwt.erl:184: :jose_jwt.sign/3
    (guardian 1.2.1) lib/guardian/token/jwt.ex:257: Guardian.Token.Jwt.create_token/3
    (guardian 1.2.1) lib/guardian.ex:756: Guardian.returning_tuple/1
    (guardian 1.2.1) lib/guardian.ex:582: Guardian.encode_and_sign/4
    (ret 1.0.0) lib/ret/perms_token.ex:24: Ret.PermsToken.token_for_perms/1
    (ret 1.0.0) lib/ret_web/channels/ret_channel.ex:39: RetWeb.RetChannel.handle_in/3
    (phoenix 1.4.16) lib/phoenix/channel/server.ex:280: Phoenix.Channel.Server.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "refresh_perms_token", join_ref: "435", payload: nil, ref: "436", topic: "ret"}
State: %Phoenix.Socket{assigns: %{session_id: "4e899c16-dad9-4bc8-b782-7d2ff1f95d79", started_at: ~N[2020-04-24 08:45:52]}, channel: RetWeb.RetChannel, channel_pid: #PID<0.3890.0>, endpoint: RetWeb.Endpoint, handler: RetWeb.SessionSocket, id: "session:4e899c16-dad9-4bc8-b782-7d2ff1f95d79", join_ref: "435", joined: true, private: %{log_handle_in: :debug, log_join: :info}, pubsub_server: Ret.PubSub, ref: nil, serializer: Phoenix.Socket.V2.JSONSerializer, topic: "ret", transport: :websocket, transport_pid: #PID<0.3857.0>}

**Comment by zhang-wenhua** [comment]
[info] TLS :server: In state :abbreviated received CLIENT ALERT: Fatal - Certificate Unknown
Can you tell me how to solve this problem? Thanks a lot.

**Comment by zhang-wenhua** [comment]
thinks

**Comment by lierdakil** [comment]
@zhang-wenhua did you figure it out? I'm running into the same issue.

**Comment by lierdakil** [comment]
Nevermind. For posterity, this is what's going on and how to fix: https://github.com/mozilla/reticulum/issues/466#issuecomment-774831150

**Comment by felipersi** [comment]
my fault that let this error happen was that I was not breaking the key into lines with \n.

After adjusting the \n at the end of each line, the certificate was understood by reticulum.
