### ISSUE TITLE
can't see screen of skipadmin in my Local machine.

### ISSUE THREAD

**Issue by h-nakae** [mozilla/reticulum#423]
my problem is totally same as below link.
-----------------------------------

https://stackoverflow.com/questions/62337760/how-to-run-mozilla-hubs-on-my-local-machine

I think I followed the instruction, but the URL which is 'https://hubs.local:4000?skipadmin ' returns white page says 'Missing file index.html. Please try again.' as pasted here.
![image](https://user-images.githubusercontent.com/56616438/95907494-98a45100-0dd6-11eb-9966-9b1fa1bdb311.png)

My current emviroment is like this.
-----------------------------------

Ubunts 18.04
nodeJS = v12.19.0
(PostgreSQL) 11.9
Elixir 1.10.4 (compiled with Erlang/OTP 22)
ansible 2.9.14
python version = 2.7.17
hubs⇒ cloned from the original repository today

The output of reticulum console when accessed the url is like this..
-----------------------------------

[debug] QUERY OK db=0.1ms decode=1.7ms queue=7.4ms idle=0.0ms
CREATE SCHEMA IF NOT EXISTS ret0 []
[debug] QUERY OK db=0.1ms queue=1.2ms idle=6.1ms
CREATE SCHEMA IF NOT EXISTS coturn []
[debug] QUERY OK db=5.7ms queue=0.1ms idle=7.3ms
ALTER DATABASE ret_dev SET search_path TO ret0 []
[info] Already up
[debug] QUERY OK db=7.6ms queue=0.4ms idle=28.4ms
INSERT INTO coturn.turn_secret (realm, value, inserted_at, updated_at) values ($1, $2, now(), now()) ["ret", "e35e79c7b17b33758fe8147497f2b99f"]
[debug] QUERY OK db=0.6ms queue=0.5ms idle=17.5ms
DELETE FROM coturn.turn_secret WHERE inserted_at < now() - interval '15 minutes' []
[info] Running RetWeb.Endpoint with cowboy 2.6.3 at 0.0.0.0:4000 (https)
[info] Access RetWeb.Endpoint at https://hubs.local:4000
Interactive Elixir (1.10.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 04:37:30 - info: compiled 6 files into 2 files, copied 2 in 1.0 sec
[info] TLS :server: In state :certify received CLIENT ALERT: Fatal - Certificate Unknown

[info] GET /
[debug] Processing with RetWeb.PageController
  Parameters: [UNFETCHED]
  Pipelines: [:secure_headers, :parsed_body, :browser]
[debug] QUERY OK source="app_configs" db=0.9ms queue=0.9ms idle=9281.6ms
SELECT a0."app_config_id", a0."key", a0."value", a0."owned_file_id", a0."inserted_at", a0."updated_at" FROM "ret0"."app_configs" AS a0 WHERE (a0."key" = $1) ["features|default_room_id"]
[debug] QUERY OK source="app_configs" db=0.5ms queue=1.0ms idle=8285.3ms
SELECT a0."app_config_id", a0."key", a0."value", a0."owned_file_id", a0."inserted_at", a0."updated_at" FROM "ret0"."app_configs" AS a0 []
[info] Sent 503 in 10040ms

I am waiting for your replying.
Thanks.

**Comment by truedat101** [comment]
I can confirm the same error on my system:

```
iex(7)> [info] GET /
[debug] Processing with RetWeb.PageController
  Parameters: [UNFETCHED]
  Pipelines: [:secure_headers, :parsed_body, :browser]
[debug] QUERY OK source="app_configs" db=1.7ms idle=9229.7ms
SELECT a0."app_config_id", a0."key", a0."value", a0."owned_file_id", a0."inserted_at", a0."updated_at" FROM "ret0"."app_configs" AS a0 WHERE (a0."key" = $1) ["features|default_room_id"]
[debug] QUERY OK source="app_configs" db=0.5ms idle=8231.5ms
SELECT a0."app_config_id", a0."key", a0."value", a0."owned_file_id", a0."inserted_at", a0."updated_at" FROM "ret0"."app_configs" AS a0 []
[info] Sent 503 in 10006ms
```

**Comment by truedat101** [comment]
The skipadmin is supposed to avoid having to login using the email links .  The problem is that it isn't finding the index.html file .  I notice an index.html file in the root level of the project.  I am having trouble otherwise understanding the phoenix framework arpproach.  I suggest we look through https://github.com/phoenixframework/phoenix and figure it out.

**Comment by robinaguilar713** [comment]
I’m able to run both Pheonix and Hub servers and they both load their respective landing pages. 
Pheonix is being accessed through both localhost:4000 and hubs.local:4000
Hubs is being accessed through hubs.local:8080

When I try accessing through hubs.local:4000?skipadmin I get the same index.html landing page from the Phoenix server. 

Here’s the response from the terminal:

```
info] CONNECTED TO Phoenix.LiveView.Socket in 109µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "OzYxARsEDEVvJHhbD0I6e2cbJX84ejITKLffh5K-ZaKju5k30KcOB6Qd", "_mounts" => "0", "_track_static" => %{"0" => "http://localhost:4000/css/app.css", "1" => "http://localhost:4000/js/app.js"}, "vsn" => "2.0.0"}
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{}
  Pipelines: [:browser]
[info] Sent 200 in 515µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 96µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "XSl4Jl80UTIbFXN0OA8WXSQBHgd2JDpg-aLWmm8EXV7MUNUlegVt8ek3", "_mounts" => "0", "_track_static" => %{"0" => "http://hubs.local:4000/css/app.css", "1" => "http://hubs.local:4000/js/app.js"}, "vsn" => "2.0.0"}
[info] GET /
[debug] Processing with Phoenix.LiveView.Plug.index/2
  Parameters: %{"skipadmin" => ""}
  Pipelines: [:browser]
[info] Sent 200 in 752µs
[info] CONNECTED TO Phoenix.LiveView.Socket in 122µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"_csrf_token" => "XSl4Jl80UTIbFXN0OA8WXSQBHgd2JDpg-aLWmm8EXV7MUNUlegVt8ek3", "_mounts" => "0", "_track_static" => %{"0" => "http://hubs.local:4000/css/app.css", "1" => "http://hubs.local:4000/js/app.js"}, "vsn" => "2.0.0"}
```

The response is the same from all three host/port configurations.

As I understand it, the Hubs server is supposed to be configured to be accessed through the Pheonix server at hubs.local:4000 but the directions for this step are not in the documentation.

**Comment by truedat101** [comment]
@robinaguilar713  hoping someone with some experience running this project  (or with phoenix) chimes in.   I'll continue to dip into documentation.  Sometimes people post more helpful set up guides on places like youtube.

**Comment by truedat101** [comment]
One other detail that may be an issue is the setting of the CORS server.  Experiment with changing the config so that you are running a local CORS.  The other thing not documented is that https://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html#environments , noting that MIX_ENV is the variable used to choose the environment, although it seems Elixer defaults to dev mode.

**Comment by robinkwilson** [comment]
To fix the missing index.html issue (worked for me)-> mozilla/reticulum#425

**Comment by truedat101** [comment]
@robinaguilar713 heads up.   Looks like maybe a fix.

**Comment by h-nakae** [comment]
@robinkwilson 
Thanks, it works fine for me.

**Comment by rvanlieshout** [comment]
This error is to be found in:

```elixir
  defp try_chunks_for_page(conn, page, source) do
    res =
      if module_config(:skip_cache) do
        PageOriginWarmer.chunks_for_page(source, page)
      else
        Cachex.get(:page_chunks, {source, page})
      end

    case res do
      {:ok, chunks} = res when chunks != nil -> res
      _ -> {:error, conn |> send_resp(503, "Missing file #{page}. Please try again.")}
    end
  end
```

In my case I was missing cache entries because of an absence of Ret.PageOriginWarmer in prod.exs. Once I added

```elixir
config :ret, Ret.PageOriginWarmer,
  hubs_page_origin: "https://hubs.local:8080",
  admin_page_origin: "https://hubs.local:8989",
  spoke_page_origin: "https://hubs.local:9090",
  insecure_ssl: true

config :ret, Ret.HttpUtils, insecure_ssl: true
```

to my prod.esx and once I made sure there was something running on ports 8080 (https://github.com/mozilla/reticulum#3-start-the-hubs-webpack-dev-server) it was all good. Wait for PageOriginWarmer to update the cache after a phx.server boot. If you access it before that's ready you'll still get the Missing file index.html.

This Phoenix application fetches data from other endpoints. These endpoints need to be available. Note that one should never use insecure_ssl-like options in a production environment!

**Comment by truedat101** [comment]
@rvanlieshout thanks this is the best description of the root cause that I've seen so far.

**Comment by albirrkarim** [comment]
any solution?

**Comment by albirrkarim** [comment]
after i fix the missing index.html issue. im faces this problem 

https://github.com/mozilla/reticulum/issues/496#issue-891181574
