### ISSUE TITLE
Dockerfile build fails on the yarn step

### ISSUE THREAD

**Issue by truedat101** [mozilla/reticulum#434]
The Dockerfile build fails on the yarn step with an unexpected token error, described:

https://github.com/yarnpkg/yarn/issues/6914

While the yarn install bug seems related to the version of node on the system, "just upgrading node" might not be a solution in the container of the Elixer base.  Commenting out this yarn install line works.  Not sure why yarn is needed if npm would always be available if node is installed.

**Comment by brianpeiris** [comment]
The docker-compose file we have in this repo is very outdated, so I'm closing this for now. We might resolve this relatively soon with a proper docker setup.
