### ISSUE TITLE
Media resolver suggestion: screenshot fallback for failed media resolution

### ISSUE THREAD

**Issue by misslivirose** [mozilla/reticulum#435]
We occasionally get reports that websites with embedded videos fail to resolve properly and display as a broken media link. While we use the screenshot service if other media types aren't detected, we may want to re-work how videos and general websites "break" if there is an unresolved response. In many cases (e.g. I'm pasting a URL to a website that has an embedded video on it) it would be preferable to see a screenshot than a broken media image.

**Comment by misslivirose** [comment]
Updating this to include other websites as examples where the screenshot code is failing per this issue here: https://github.com/mozilla/hubs/issues/3654

**Comment by johnshaughnessy** [comment]
This PR https://github.com/mozilla/reticulum/pull/452 does not fix 100% of the issue we have been seeing. I have opened a new issue to address its shortcomings. https://github.com/mozilla/reticulum/issues/455

**Comment by MegaMotion** [comment]
I am wondering if this is the same bug I am experiencing... I have a sit that has been up since last June, with many images uploaded using the magic wand tool and others hosted externally. They were all working before, but now a large number of them show broken links, even though the image is fine if I go to "open link" in hubs. Others work fine. Is there any way to reset or fix this? Will this PR do it?

**Comment by visioninglab** [comment]
I am having the same problem - put URL in hub, works fine as a link but shows a broken link image. Ironically the link is https://hubs.mozilla.com/docs/hubs-features.html. Thought it might be an https problem so tried http://hubs.mozilla.com/docs/hubs-features.html. Same problem links fine but shows up as a broken link in the hub. Any tips? It's embarrassing to show a broken link even if it actually works

**Comment by ConstantChange** [comment]
Any attempt to create a link with the magic wand results in a broken in link in our HC deployment.
