### ISSUE TITLE
A quick question, what service is supposed to be exposed on port 6000?

### ISSUE THREAD

**Issue by lierdakil** [mozilla/reticulum#465]
Basically, see the title.

Specifically, talking about this:

https://github.com/mozilla/reticulum/blob/566af5d65265e6eb07504ed3dc3cefd672b1dd85/lib/ret_web/plugs/proxies.ex#L6-L9

I get that `Ita` probably means "IT Automation", but I don't understand what _specifically_ is supposed to be there.

Sorry if it's a wrong place to ask this question, but I've just spent about 4 hours trying to figure it out from commit messages, docs, reading scripts in hubs-ops, came up absolutely empty, and it's slowly driving me crazy.

Thanks in advance.

**Comment by worph** [comment]
It is related to Hubs AWS management => https://bldr.habitat.sh/#/pkgs/mozillareality/ita/latest

**Comment by lierdakil** [comment]
Thanks, that's one mystery solved.

I was hoping sources are available somewhere, but apparently not? Oh well, as far as I can tell it's not a critical component, everything seems to work without, except some parts of the admin panel and a frontend deployment script.

**Comment by mkg20001** [comment]
From https://bldr.habitat.sh/#/pkgs/mozillareality/ita/latest

```
do_install() {
  # take care not to include unminified ita source
  for p in node_modules dist schemas
```

I wonder what the motivation behind not publishing the sources is?

**Comment by baohiep83** [comment]
@lierdakil Could you help me showing step by step how to config habitat run on port 6000? I did following steps:
1. cd /reticulum. I run hab studio enter
2. build habitat
3. hab svc load mozillareality/reticulum
But I still get error when I accessed admin page, and when I click on any function of menu, system logout.
![image](https://user-images.githubusercontent.com/42344684/132835580-b6eadcae-b7ea-4378-8f38-6041c0919025.png)

**Comment by albirrkarim** [comment]
Instead of using `localhost:6000` for ita and using `localhost:3000` for postgres which is we can't find the source code.

Maybe we need to make the backend code by ourselves using elixir

**Comment by brianpeiris** [comment]
Ita is a service that we use to configure Hub's other services when it is running in AWS. It does not need to be setup or used when you are running the hubs services locally, since you can configure those service directly yourselves. You can essentially ignore the errors related to Ita when using the admin panel.
We may address the need for self-hosting and the admin panel in other ways as the product continues to evolve.
