### ISSUE TITLE
join crashed

### ISSUE THREAD

**Issue by lierdakil** [mozilla/reticulum#466]
Running a local reticulum server with hubs, I get `join crashed` in browser console, and the following error trace in reticulum console:

```
 [error] an exception was raised:
     ** (ArgumentError) argument error: [[], {:jose_jws, {:jose_jws_alg_rsa_pkcs1_v1_5, :RS512}, :undefined, %{"typ" => "JWT"}}, %{"account_id" => "897854010768228357", "aud" => :ret_perms, "close_hub" => true, "create_hub" => true, "embed_hub" => true, "exp" => 1612741759, "fly" => true, "hub_id" => "pyRtM5s", "iat" => 1612741459, "iss" => "", "join_hub" => true, "jti" => "3c53baa9-1471-4afe-9192-18ba0b807802", "kick_users" => true, "mute_users" => true, "nbf" => 1612741458, "pin_objects" => true, "spawn_and_move_media" => true, "spawn_camera" => true, "spawn_drawing" => true, "spawn_emoji" => true, "sub" => "897854010768228357_pyRtM5s", "tweet" => false, "typ" => "access", "update_hub" => true, "update_hub_promotion" => false, "update_roles" => true}]
         (jose) src/jwt/jose_jwt.erl:184: :jose_jwt.sign/3
         (guardian) lib/guardian/token/jwt.ex:259: Guardian.Token.Jwt.create_token/3
         (guardian) lib/guardian.ex:765: Guardian.returning_tuple/1
         (guardian) lib/guardian.ex:594: Guardian.encode_and_sign/4
         (ret) lib/ret/perms_token.ex:24: Ret.PermsToken.token_for_perms/1
         (ret) lib/ret_web/channels/hub_channel.ex:1039: RetWeb.HubChannel.join_with_hub/5
         (phoenix) lib/phoenix/channel/server.ex:375: Phoenix.Channel.Server.channel_join/4
         (phoenix) lib/phoenix/channel/server.ex:257: Phoenix.Channel.Server.handle_info/2
         (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
         (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
         (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I don't know enough elixir/erlang to figure this out. Any help?

**Comment by lierdakil** [comment]
I've figured it out by staring at the sources for several hours.

For posterity, `config :ret, Ret.PermsToken, perms_key` needs to be set to a valid RSA private key. One such key can be found in `config/test.exs`. For some reason, the default `dev.exs` doesn't specify a key.

**Comment by robinaguilar713** [comment]
@lierdakil were you able to figure this out? I don't know much about elixir, I just copied the RSA over to dev.exs based on your comment and that allowed me to get past the server error but I'm wondering if you were able to properly set the config. I still can't create the admin user for some reason, getting an undefined function error in the iex console.

**Comment by richardbarrell-calvium** [comment]
@lierdakil Thank you so much <3

**Comment by nicokruger** [comment]
Just ran intho this as well, thanks @lierdakil . Perhaps this should be added to readme ? Not sure how it can work for others without this step...

**Comment by albirrkarim** [comment]
> I've figured it out by staring at the sources for several hours.
> 
> For posterity, `config :ret, Ret.PermsToken, perms_key` needs to be set to a valid RSA private key. One such key can be found in `config/test.exs`. For some reason, the default `dev.exs` doesn't specify a key.

So what changes did you make on the `dev.exs` for fixing this issue? I'm new to this file format

**Comment by albirrkarim** [comment]
> I've figured it out by staring at the sources for several hours.
> 
> For posterity, `config :ret, Ret.PermsToken, perms_key` needs to be set to a valid RSA private key. One such key can be found in `config/test.exs`. For some reason, the default `dev.exs` doesn't specify a key.

Im doing this. This is PermsToken from `test.exs` i copy it and comment PermsToken on the `dev.exs` and paste in the next line. like this picture

![image](https://user-images.githubusercontent.com/29292018/152142723-b85efb26-b403-453a-9721-b8188e7d3d4e.png)

Yeah the join crashed error in browser console is fixed. But i got another error like this


<img width="1552" alt="Screen Shot 2022-02-02 at 18 12 33" src="https://user-images.githubusercontent.com/29292018/152143386-b768bcaa-32ec-4dcf-b108-324693098859.png">
