### ISSUE TITLE
Prevent accidental merges to master branch

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/reticulum#470]
Accidentally pushing code to master branch could cause jenkins to run a migration that would be difficult to undo / recover from. We should take some action to reduce the risk of this happening.
Examples:
- Find a way to enforce a git hook (https://github.com/mozilla/hubs/pull/3738)
- Only allow commits to be added to master by merging pull requests

**Comment by brianpeiris** [comment]
This is less of a concern with our new infrastructure, and we already have some branch protection in please, so I'm going to close this, but we may still have to think of strategies for safely running migrations during deploys to production.
