### ISSUE TITLE
can not run latest reticulum fine locally with latest hubs

### ISSUE THREAD

**Issue by h-nakae** [mozilla/reticulum#496]
Hi,

In the past, I could run hubs which has old UI on reticulum locally fine.
But with latest revision of them as following, I can not run them fine.

hubs: https://github.com/mozilla/hubs/commit/6c3afd50137099d8564f5534fb2cca5f68655521
reticulum: https://github.com/mozilla/reticulum/commit/d185616c4069d73785ecaf37dbc028e26bc0f363

I really would like to know the solution to run hubs has new UI on reticulum locally.

My environment is as following.
OS: Windows 10 + WSL(Ubuntu 18.04)
postgreSQL@11
Elixir: 1.11.2 with Erlang/OTP 23
phoenix: 1.5.9
ansible installed as instruction
node: v12.20

When I run them and open "https://hubs.local:4000/?skipadmin",
I got just white blank page, and many errors say "net::ERR_CERT_AUTHORITY_INVALID" on console.
![hubs_error_skipadmin](https://user-images.githubusercontent.com/56616438/118153232-a1363600-b450-11eb-94aa-b10f376f0917.PNG)

And when trying to entering room, I got other errors like following pic.
![entring_room_error_hubs](https://user-images.githubusercontent.com/56616438/118153515-f5d9b100-b450-11eb-9f31-9dbb5c54a9e7.PNG)

Actually I have tried them on mac, pure ubuntu environment.
Besides I have tried other version of hubs and reticulum with reference to the repository of hubs cloud↓.
https://github.com/mozilla/hubs-cloud/blob/master/CHANGELOG.md
But unfortunately everything did not go well..

I am waiting for your answering.
Sincerely yours.
Hironori

**Comment by keianhzo** [comment]
@h-nakae That sounds to me like you need to approve the certificate for the urls that are getting rejected. Try to open a new tab and go to https://hubs.local:8080 and accept the certificate and try again.

**Comment by baohiep83** [comment]
I got this issue and solved as follow on chrome:
1. add hubs.local into chrome://flags/ --> Insecure origins treated as secure
2.  delete cache
3. go to https://hubs.local:8080 and accept the certificate and try again.

**Comment by albirrkarim** [comment]
> When I run them and open "https://hubs.local:4000/?skipadmin", I got just white blank page, and many errors say "net::ERR_CERT_AUTHORITY_INVALID" on console. ![hubs_error_skipadmin](https://user-images.githubusercontent.com/56616438/118153232-a1363600-b450-11eb-94aa-b10f376f0917.PNG)

im faces same issue
