### ISSUE TITLE
Nothing is showing up.

### ISSUE THREAD

**Issue by ryo-89287** [mozilla/reticulum#497]
Hello.
I followed the setup as per the ReedMe instructions. After that, I accessed the https://hubs.local:4000?skipadmin, but nothing is displayed.
No errors are shown in the server logs.

During the procedure, I did npm install in the assets directory, but nothing is installed, because there is no package.json.
Is it because nothing is installed that I don't see anything?

How can I set up a local development environment?

Please help me.

**Comment by keianhzo** [comment]
What do you see in the browser console? See if it's related to this: https://github.com/mozilla/reticulum/issues/496
