### ISSUE TITLE
error in feature/phoenix-1.5

### ISSUE THREAD

**Issue by ruliusuifeng** [mozilla/reticulum#513]
I try to use branch feature/phoenix-1.5
when I connected https://hubs.local:4000/
[error] Ranch listener RetWeb.Endpoint.HTTPS had connection process started with :cowboy_tls:start_link/4 at #PID<0.958.0> exit with reason: {:undef, [{:ssl, :ssl_accept, [{:sslsocket, {:gen_tcp, #Port<0.99>, :tls_connection, [option_tracker: #PID<0.591.0>, session_tickets_tracker: :disabled, session_id_tracker: #PID<0.592.0>]}, [#PID<0.957.0>, #PID<0.956.0>]}, [], 5000], []}, {:ranch_ssl, :handshake, 3, [file: '/www/wwwroot/good/reticulum/deps/ranch/src/ranch_ssl.erl', line: 142]}, {:ranch, :handshake, 2, [file: '/www/wwwroot/good/reticulum/deps/ranch/src/ranch.erl', line: 243]}, {:cowboy_tls, :connection_process, 4, [file: '/www/wwwroot/good/reticulum/deps/cowboy/src/cowboy_tls.erl', line: 43]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}

**Comment by brianpeiris** [comment]
We'll have to revisit this when merging #460
