### ISSUE TITLE
Running Reticulum localy

### ISSUE THREAD

**Issue by RoxyBoxxy** [mozilla/reticulum#526]
I have managed to compile deps and the hubs page is trying to put me in a lobby how ever it stops at loading scene and i get this error

```bash
[error] an exception was raised:
    ** (ArgumentError) argument error: [[], {:jose_jws, {:jose_jws_alg_rsa_pkcs1_v1_5, :RS512}, :undefined, %{"typ" => "JWT"}}, %{"account_id" => "1066633804673712131", "amplify_audio" => true, "aud" => :ret_perms, "close_hub" => true, "create_hub" => true, "embed_hub" => true, "exp" => 1632860232, "fly" => true, "hub_id" => "fpLcDD2", "iat" => 1632859932, "
iss" => "", "join_hub" => true, "jti" => "edae2140-cedf-4351-8faa-bf0ec2b9fae6", "kick_users" => true, "mute_users" => true, "nbf" => 1632859931, "pin_objects" => true, "spawn_and_move_media" => true, "spawn_camera" => true, "spawn_drawing" => true, "spawn_emoji" => true, "sub" => "1066633804673712131_fpLcDD2", "tweet" => false, "typ" => "access", "update_hub" => true, "update_hub_promotion" => false, "update_roles" => true}]
        (jose) src/jwt/jose_jwt.erl:184: :jose_jwt.sign/3
        (guardian) lib/guardian/token/jwt.ex:259: Guardian.Token.Jwt.create_token/3
        (guardian) lib/guardian.ex:765: Guardian.returning_tuple/1
        (guardian) lib/guardian.ex:594: Guardian.encode_and_sign/4
        (ret) lib/ret/perms_token.ex:24: Ret.PermsToken.token_for_perms/1
        (ret) lib/ret_web/channels/hub_channel.ex:1039: RetWeb.HubChannel.join_with_hub/5
        (phoenix) lib/phoenix/channel/server.ex:375: Phoenix.Channel.Server.channel_join/4
        (phoenix) lib/phoenix/channel/server.ex:257: Phoenix.Channel.Server.handle_info/2
        (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/HUBS-1084)

**Comment by ipeakermit** [comment]
Any update on this?

**Comment by albirrkarim** [comment]
I don't know your issue guys.

I have done running hubs project on localhost

Check out my tutorial for [running hubs project locally](https://github.com/albirrkarim/mozilla-hubs-installation-detailed) and give me repo star if you think this is very helpful

**Comment by justincolangelo** [comment]
> I don't know your issue guys.
> 
> I have done running hubs project on localhost
> 
> Check out my tutorial for [running hubs project locally](https://github.com/albirrkarim/mozilla-hubs-installation-detailed) and give me repo star if you think this is very helpful

It's great that you were able to get it running. Those instructions make sense after going through the setup ourselves a bunch of times and running into issues. This issue in particular was solved by setting the perms token correctly `config :ret, Ret.PermsToken, perms_key:` as you show in your setup document. We eventually figured that part out.

**Comment by ArdaKonut** [comment]
Any updates on this issue?
