### ISSUE TITLE
503 returned while running "iex -S mix phx.server"

### ISSUE THREAD

**Issue by NagarajuSamudrala** [mozilla/reticulum#540]
Hello,

After installing the Reticulum and opening the webpage in Chrome browser, getting error as shown in the screen shot.
(Step : iex -S mix phx.server)

Environment:
Ubuntu 18
Erlang/OTP 23

![image](https://user-images.githubusercontent.com/97037908/148086704-cd1538bd-2ced-4b54-b53b-8f2f6392ead9.png)

Console logs look like follows (HTTP Error 503 returned)

![image](https://user-images.githubusercontent.com/97037908/148087389-38e815d8-de99-4178-ab48-2f4100726a81.png)

Getting following error :
**TLS :server: In state :certify received CLIENT ALERT: Fatal - Certificate Unknown**

Please suggest how to fix the same.

Thanks,
Nagaraju Samudrala

**Comment by NagarajuSamudrala** [comment]
After compiling hubs, this error is taken care

Thanks,

**Comment by albirrkarim** [comment]
I think this will fix your issue https://github.com/mozilla/reticulum/issues/423#issuecomment-754997322

**Comment by albirrkarim** [comment]
> After compiling hubs, this error is taken care
> 
> Thanks,

How to doing that sir?

**Comment by kouzzy** [comment]
I am also suffering from this problem. 
I don't think it can be solved just by compiling hubs, but how did you solve it?

**Comment by albirrkarim** [comment]
I have solved this problem, by doing this

https://github.com/albirrkarim/mozilla-hubs-installation-detailed

**Comment by kouzzy** [comment]
Thanks to that, the outlook has become brighter.
By the way, where is turnserver.conf (Dialog configuration file)?

**Comment by kouzzy** [comment]
very. It was a great hint to solve the problem. thank you.
