### ISSUE TITLE
Error: JsonWebTokenError: invalid signature when creating room in https://hubs.local:4000/?skipadmin

### ISSUE THREAD

**Issue by albirrkarim** [mozilla/reticulum#550]
Here is my journey on installing Mozilla Hubs Locally 

**My devices:**
Macbook Air M1 
Mac OS 12.1

Im clone two project **Hubs** and this **reticulum**

**On hubs directory i do:**
`npm install`
`npm run local` (to start the hubs.local:8080)

**On reticulum directory:**
Installing elixir 1.12 and erlang 23 using asdf
Installing postgres pqsl by using https://postgresapp.com/downloads.html

run with `iex -S mix phx.server` (to start hubs.local:4000)

Then fixing this SSL issue https://github.com/mozilla/reticulum/issues/496#issue-891181574 by using mozilla firefox to bypass because when im using chrome i can't doing that.

and fixing the https://github.com/mozilla/reticulum/issues/466#issue-803092945 with this https://github.com/mozilla/reticulum/issues/466#issuecomment-1027834312 

So now i can access the https://hubs.local:4000/?skipadmin

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/29292018/152265638-98f537d7-8f55-40a3-b784-723946825ef0.png">

But if i click the create room button, it take me to a new page like this picture bellow. Loading stuff and then it crash. on the console i got this error says JsonWebTokenError

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/29292018/152264258-2cf0db51-9696-41c6-9e4b-08715d1cb676.png">

Thanks for reading my stories

Please share your journey on installing the mozilla hubs locally, maybe we have same problem

**Comment by albirrkarim** [comment]
Solved with this https://github.com/mozilla/hubs/discussions/3323#discussioncomment-1857495 and installing [dialog](https://github.com/mozilla/dialog)

**Comment by albirrkarim** [comment]
Solved with this https://github.com/mozilla/hubs/discussions/3323#discussioncomment-1857495 and installing [dialog](https://github.com/mozilla/dialog)

**Comment by nupur711** [comment]
> Here is my journey on installing Mozilla Hubs Locally
> 
> **My devices:** Macbook Air M1 Mac OS 12.1
> 
> Im clone two project **Hubs** and this **reticulum**
> 
> **On hubs directory i do:** `npm install` `npm run local` (to start the hubs.local:8080)
> 
> **On reticulum directory:** Installing elixir 1.12 and erlang 23 using asdf Installing postgres pqsl by using https://postgresapp.com/downloads.html
> 
> run with `iex -S mix phx.server` (to start hubs.local:4000)
> 
> Then fixing this SSL issue [#496 (comment)](https://github.com/mozilla/reticulum/issues/496#issue-891181574) by using mozilla firefox to bypass because when im using chrome i can't doing that.
> 
> and fixing the [#466 (comment)](https://github.com/mozilla/reticulum/issues/466#issue-803092945) with this [#466 (comment)](https://github.com/mozilla/reticulum/issues/466#issuecomment-1027834312)
> 
> So now i can access the https://hubs.local:4000/?skipadmin
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/29292018/152265638-98f537d7-8f55-40a3-b784-723946825ef0.png">
> 
> But if i click the create room button, it take me to a new page like this picture bellow. Loading stuff and then it crash. on the console i got this error says JsonWebTokenError
> 
> <img alt="image" width="1552" src="https://user-images.githubusercontent.com/29292018/152264258-2cf0db51-9696-41c6-9e4b-08715d1cb676.png">
> 
> Thanks for reading my stories
> 
> Please share your journey on installing the mozilla hubs locally, maybe we have same problem

How you installed reticulum server, I am getting this error
<img width="998" alt="image" src="https://user-images.githubusercontent.com/28728455/152559484-479a2c02-62d2-4352-8c0d-9290d2a330c3.png">

**Comment by albirrkarim** [comment]
> How you installed reticulum server, I am getting this error <img alt="image" width="998" src="https://user-images.githubusercontent.com/28728455/152559484-479a2c02-62d2-4352-8c0d-9290d2a330c3.png">

it mean password or something information to connect with postgres database are wrong. you can setting it in /config/dev.exs

just follow the default

![image](https://user-images.githubusercontent.com/29292018/152609889-8b29032a-d9df-44d8-8781-f0b46ec8817e.png)
