### ISSUE TITLE
Where are Objects Links are stored on?

### ISSUE THREAD

**Issue by liqiang1995** [mozilla/reticulum#594]
I am going to make a function to modify the room objects(pictures and videos).
But I can not find the object links in the database.
Are we store the links as a file?
Could you please let me know it?
Thank you.

**Comment by brianpeiris** [comment]
The RoomObject module/schema determines how objects are persisted in rooms: https://github.com/mozilla/reticulum/blob/master/lib/ret/room_object.ex
