### ISSUE TITLE
Error while running reticulum on iMac with command iex -S mix phx.server

### ISSUE THREAD

**Issue by monukbizsoft** [mozilla/reticulum#648]
HI,

I'm trying to run the reticulum on Mac 

elixir 1.8.2 / erlang 23.3.4.26 installed.

Steps:
mix deps.get
mix ecto.create

Done successfully.

Directory storage/dev created inside the reticulum folder.

Running iex -S mix phx.server on an elevated administrator terminal, and getting error:

**== Compilation error in file lib/ret/schema.ex ==
** (CompileError) lib/ret/schema.ex:39: call to local macro is_struct/1 conflicts with imported Kernel.is_struct/1, please rename the local macro or remove the conflicting import
(elixir 1.14.2) expanding macro: Kernel.and/2
lib/ret/schema.ex:39: Ret.Schema.is_schema/1
(elixir 1.14.2) expanding macro: Kernel.and/2
lib/ret/schema.ex:40: Ret.Schema.is_schema/1
(elixir 1.14.2) expanding macro: Kernel.Utils.defguard/2
lib/ret/schema.ex: Ret.Schema.is_schema/1**

Please check the screenshots:

![error](https://user-images.githubusercontent.com/119565686/204987485-770f4c74-0acf-44af-bf0d-5e438c7b249e.png)

Installed the version of elixir and erlang per your suggestion
**% asdf current**
elixir          **1.8.2**           /Users/iMac/Documents/Work/Hub test/reticulum/.tool-versions
erlang          **22.3.4.26**       /Users/iMac/Documents/Work/Hub test/reticulum/.tool-versions

======================
Also, I have tried the same with updated erlang **25.1.2** and still got same error in new folder

Any help would be appreciated.

Thanks a lot,
Monu k.

**Comment by rawnsley** [comment]
I don’t know anything about this error specifically, but I *highly* recommend running reticulum and any other Hubs service in Docker rather than locally as described here https://github.com/mozilla/hubs-compose

**Comment by bryanenders** [comment]
You appear to have a newer version of Elixir (v1.14.2) in your shell’s PATH. You can run **$**&nbsp;`which elixir` to find out where it’s located. You can run **$**&nbsp;`echo $PATH` to see the directories in your PATH. If you want to keep Elixir v1.14.2 installed alongside asdf but default to the asdf install, you will need to move `~/.asdf/shims` toward the front of your PATH.

I hope this helps!

**Comment by monudev** [comment]
I have added ~/.asdf/shims at the top of the path file in the etc folder

But we need to add the full path of the home directory instead of the ~ operator

This is the right solution.

Thanks @bryanenders

**Comment by monukbizsoft** [comment]
Hi
I am facing same error on live server 

Server VPS with ubuntu 20

Please check error: 
```
== Compilation error in file lib/ret/schema.ex ==
** (CompileError) lib/ret/schema.ex:39: call to local macro is_struct/1 conflicts with imported Kernel.is_struct/1, please rename the local macro or remove the conflicting import
    (elixir 1.12.3) expanding macro: Kernel.and/2
    lib/ret/schema.ex:39: Ret.Schema.is_schema/1
    (elixir 1.12.3) expanding macro: Kernel.and/2
    lib/ret/schema.ex:40: Ret.Schema.is_schema/1
    (elixir 1.12.3) expanding macro: Kernel.Utils.defguard/2
    lib/ret/schema.ex: Ret.Schema.is_schema/1
    (elixir 1.12.3) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I have added .asdf/shims in first possition into $PATH file
```
**echo $PATH**
/root/.asdf/shims:/root/.asdf/bin:/root/.nvm/versions/node/v16.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```


I am using below version of elixir and erlang
```
**# asdf current**
elixir          1.12.3          /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
erlang       23.3            /hubs/hubs-actions-runner/reticulum/_work/reticulum/reticulum/.tool-versions
```

Thanks
