### ISSUE TITLE
configure RetWeb.Endpoint

### ISSUE THREAD

**Issue by OurBigAdventure** [mozilla/reticulum#73]
Is there any way someone can clarify the ReadMe about configuring the RetWeb.Endpoint?  It is pretty vague and not very helpful to those discovering the project for the first time.

**Comment by brianpeiris** [comment]
I've edited the readme to be a bit clearer hopefully. Basically you'll probably want to change the host from `hubs.local` to `localhost`. (We use `hubs.local` on our team by configuring local HOSTS files to unify local development flows)
